Catkin-ProjectName: genpybindings
Version: 0.0.5
Description: Willow Garage low level build system macros and infrastructure
Author: Troy Straszheim <straszheim@willowgarage.com>, Morten Kjaergaard
Maintainer: Troy Straszheim <straszheim@willowgarage.com>
Homepage: http://www.ros.org

Depends: catkin, genmsg, libboost-python-dev

Catkin-CopyrightType:  willowgarage
Catkin-ROS-Message-Generator: pybindings
Catkin-DebRulesType: cmake

